default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

production:
  <<: *default
  url: <%= ENV["DATABASE_URL_2"] %>

development:
  <<: *default
  database: fogcityrun
  username: maxmetcalfe
  password:
  host: localhost

test:
  <<: *default
  database: travis_ci_test
  username: postgres
  password:
  host: localhost
