name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.5.8']
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install bundler
      run: gem install bundler -v 1.17.3
    - name: Install dependendies for build
      run: bundle install
    - name: Install dependencies for ${{ matrix.rails-version }}
      run: bundle exec appraisal ${{ matrix.rails-version }} bundle install
    - name: Run tests
      run: bundle exec appraisal ${{ matrix.rails-version }} rake
